name: Build and deploy dev/PR
on:
  workflow_call:
  push:
    branches:
      - main
    # tags:
    #   - "v**"
  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
  #     - reopened
  #   branches:
  #     - main

env:
  ACTION_RUNNER: microk8s-runner-1

jobs:
  build-frontend:
    uses: .github/workflow-templates/build-docker-image.yaml
    with:
      DOCKER_CONTEXT: ./frontend
      DOCKERFILE_NAME: Dockerfile
      IMAGE_NAME: "gig3r-frontend"
      IMAGE_TAG: ${{ github.sha }}
    secrets: inherit
  build-backend:
    runs-on: ${{ env.ACTION_RUNNER }}
    steps:
      - name: placeholder
        run: "echo this is just placeholder job waiting for backend"
  
  deploy-helm-chart:
    uses: .github/workflow-templates/deploy-helm-chart.yaml
    needs:
      - build-frontend
      - build-backend
    with:
      HELM_ENVIRONMENT: dev
      HELM_FRONTEND_IMAGE: "mivalsten/gig3r-frontend"
      HELM_FRONTEND_TAG: ${{ github.sha }}
    secrets: inherit
